### ISSUE TITLE
we're working on hopr.network - is this account actually needed?

### ISSUE THREAD

**Issue by SCBuergel** [hopr/hopr#1]
Hi
I'm leading the open source project hopr.network (on github currently https://github.com/validitylabs/hopr) we're spinning out hopr into a new entity. Would be super helpful if we could use the account name`hopr` if you're not actively using it. Feel free to reach out!

Thanks and best wishes,
Sebastian

**Comment by kspdvader** [comment]
Actually, I am using it. There's just not much activity since it works well enough for me :)

**Comment by hopr** [comment]
Yes, I am using it. There's just not much activity since it is working well enough for me.

**Comment by SCBuergel** [comment]
ok thanks -  best of luck for your project!
